### ISSUE TITLE
AssertionError when running the testing data

### ISSUE THREAD

**Issue by yiluzhou1** [hongwang01/InDuDoNet_plus#3]
Dear author,

I've setup the environment based on requrirements.txt, and tried to run the testing data you provided in the folder "deeplesion\test". However, I got AssertionError. Do you have any idea what is wrong? Thank you!

> C:\Development\InDuDoNet_plus>python test_deeplesion.py --data_path "deeplesion/test/" --model_dir "pretrained_model/InDuDoNet+_latest.pt" --save_path "results/deeplesion/"
> ---  There exsits folder results/deeplesion//Xma/ !  ---
> ---  There exsits folder results/deeplesion//Xgt/ !  ---
> ---  There exsits folder results/deeplesion//X/ !  ---
> Loading model ...
> 
> name=InDuDoNet, Total number=1752929
> 0
> Traceback (most recent call last):
>   File "test_deeplesion.py", line 185, in <module>
>     print('Avg.time={:.4f}'.format(time_test/count))
>   File "test_deeplesion.py", line 167, in main
>     torch.cuda.synchronize()
>   File "C:\Users\yzhou\AppData\Local\miniconda3\envs\metal\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Development\InDuDoNet_plus\network\indudonet_plus.py", line 106, in forward
>     Y = op_modfp(F.relu(self.bn(Xs)) / 255)
>   File "C:\Users\yzhou\AppData\Local\miniconda3\envs\metal\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\yzhou\AppData\Local\miniconda3\envs\metal\lib\site-packages\odl\contrib\torch\operator.py", line 496, in forward
>     return OperatorFunction.apply(self.operator, x)
>   File "C:\Users\yzhou\AppData\Local\miniconda3\envs\metal\lib\site-packages\odl\contrib\torch\operator.py", line 205, in forward
>     input_arr = copy_if_zero_strides(input.cpu().detach().numpy())
>   File "C:\Users\yzhou\AppData\Local\miniconda3\envs\metal\lib\site-packages\odl\contrib\torch\operator.py", line 515, in copy_if_zero_strides
>     assert isinstance(arr, np.ndarray)
> AssertionError

**Comment by yiluzhou1** [comment]
Never mind! I re-installed the environment, and the problem was fixed!
